config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  
  devise_for :users

  resources :maps, only: [:index, :new, :create, :show]

  

end

app/models/map.rb
class Map < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 100 }
  validates :starting_latitude, presence: true
  validates :starting_longitude, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_filter :require_login
  
  def new
    @map = Map.new
  end
  
  def create
    @map = Map.new(map_params)
    if @map.save
      redirect_to @map
    else
      render :new
    end
  end
  
  def show
    @map = Map.find_by(id: params[:id])
    @map_json = @map.to_json
  end
  
  private
  
  def map_params
    params.require(:map).permit(:name, :starting_latitude, :starting_longitude)
  end
  
  def require_login
    redirect_to new_user_registration_path unless user_signed_in?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/create_account_helper.rb
module CreateAccountHelper
  def signup_with_valid_account_information
    fill_in "user_email", with: "frank@ocean.com"
    fill_in "user_password", with: "password"
    fill_in "user_password_confirmation", with: "password"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MapApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/global_header' %>

<%= javascript_tag do %>
  $(document).ready(function () {
    <%= yield :view_javascript %>
  });
<% end %>

<div class="notice"><%= notice %></div>
<div class="alert"><%= alert %></div>

<div class="main-content">
  <%= yield %>
</div>

</body>
</html>

app/views/maps/create.html.erb
<h1>Map#create</h1>
<p>Find me in app/views/map/create.html.erb</p>

app/views/maps/new.html.erb
<div class="map-new">
  <div id='map-frame'></div>
  <div class="map-form-section">
    <h1>Create a New Map</h1>
    
    <%= form_for @map, html: {:class => "map-form"} do |f| %>
      <div class="map-form-field">
        <%= f.label :name %>:
        <%= f.text_field :name %>
      </div>
      
      <div class="map-form-field">
        <%= f.label :starting_latitude %>:
        <%= f.text_field :starting_latitude %>
      </div>
      
      <div class="map-form-field">
        <%= f.label :starting_longitude %>:
        <%= f.text_field :starting_longitude %>
      </div>
      
      <%= f.submit %>
    <% end %>
    
  </div>
</div>

<% content_for :view_javascript do %>

  var mapbox = new mapboxgl.Map({
    container: 'map-frame',
    center: [-117.1630037, 32.71331587],
    zoom: 13,
    style: 'mapbox://styles/mapbox/streets-v9'
  });
  
  var initialMap = new InitialMap(mapbox, 'url(' + '<%= asset_path "marker-small.png" %>' + ')');
  
<% end %>

app/views/maps/show.html.erb
<div class="dashboard-page">
  <h1 class="map-header"></h1>
  
  <div class="dashboard-section">
    <div id="map-frame"></div>
  </div>
</div>  

<% content_for :view_javascript do %>

  var map = new MapApp.app.views.Map({
    map: new MapApp.app.models.Map(<%= @map_json.html_safe %>)
  });
  
<% end %>

app/views/shared/_global_header.html.erb
<div class="global-header full-width">
  <a href="<%= root_path %>">
    <div id="site-logo">MapApp</div>
  </a>
  
  <% if user_signed_in? %>
    <div class="sign-in-link right">
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
    </div>
  <% else %>
    <div class="sign-in-link right">
      <%= link_to "Log In", new_user_session_path %>
    </div>
    <div class="sign-in-link right">
      <%= link_to "Sign Up", new_user_registration_path %>
    </div>
  <% end %>
  
</div>

app/views/users/new.html.erb
<h1>Create an account</h1>

<%= form_for @user do |f| %>
    <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
    </div>
    <br/>

    <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
    </div>

    <br/>
    <div>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
    </div>

    <br/>
    <%= f.submit "Create account", class: "btn btn-primary" %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to MapApp</h1>
<%= link_to("Click here", new_map_path) %><span> to start a new map.</span>